---
configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_oh_my_zsh: true
configure_xcode: false
configure_nuget: true
configure_vscode_extensions: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - 'App Store'
  - Podcasts
  - 'System Settings'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/andrewcfitz/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/workspace/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc
  - .p10k.zsh

xcode_xip_filename: "Xcode-16.1.0.xip"
xcode_major_version: 16

homebrew_installed_packages:
  - artginzburg/tap/sudo-touchid  # Installing this early to avoid password prompts.
  - actionlint
  # - ansible # Installed via Pip.
  - ansible-lint
  - aria2
  - aws-nuke
  - awscli
  - bash
  - cabextract
  - cdrtools
  - cloud-provider-kind
  - cloudflare-wrangler
  - cloudflare-wrangler2
  - coreutils
  - crane
  - docker
  - docker-compose
  - dockutil
  - dosbox-x
  - exiftool
  - ffmpeg
  - fastlane
  - figlet
  - fluxcd/tap/flux
  - fontconfig
  - fswatch
  - gh
  - ghostscript
  - git
  - git-lfs
  - gnu-sed
  - go
  - helm
  - icu4c@76
  - iperf3
  - jq
  - k3sup
  - kind
  - koekeishiya/formulae/yabai
  - kompose
  - pulumi/tap/kube2pulumi
  - kubecm
  - kubernetes-cli
  - kubetail
  - kustomize
  - libusb
  - lolcat
  - lsusb
  - sandreas/tap/m4b-tool
  - mas
  - ncdu
  - nmap
  - node
  - openapi-generator
  - postgresql@14
  - powerlevel10k
  - pulumi
  - pulumi/tap/pulumictl
  - rclone
  - rbenv
  - s3cmd
  - sl
  - speedtest-cli
  - stow
  - stuntman
  # - swiftlint
  - tcptraceroute
  - tfenv
  - util-linux
  - vim
  - virtctl
  - watch
  - wget
  - wimlib
  - xcodes
  - xmlstarlet
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/bundle
  - isen-ng/dotnet-sdk-versions
  - sidneys/homebrew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - aldente
  - android-studio
  - audacity
  - balenaetcher
  - bartender
  - bluetility
  - charles
  - chatgpt
  - cinebench
  - cyberduck
  - dbeaver-community
  - discord
  - docker
  - dotnet-sdk7
  - dotnet-sdk8
  - dotnet-sdk9
  - element
  - firefox
  - font-hack-nerd-font
  - fork
  - github
  - github-copilot-for-xcode
  - google-chrome
  - iterm2
  - itermai
  - jetbrains-toolbox
  - kubecontext
  - microsoft-remote-desktop
  - mqtt-explorer
  - mysqlworkbench
  - ngrok
  - obsidian
  - openinterminal
  - peripheryapp/periphery/periphery
  - postman
  - proton-mail
  - qflipper
  - raspberry-pi-imager
  - rectangle
  - sf-symbols
  - slack
  - stats
  - steam
  - tailscale
  - the-unarchiver
  - thonny
  - utm
  - vagrant
  - visual-studio-code
  - vlc
  - coconutbattery
  - inkscape
  - jdownloader
  - warp
  - windsurf
  - wireshark

# # See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_installed_app_ids: []
# mas_email: ""
# mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
- name: nswag
  state: present # present/absent/latest, default: present
  version: "^14.2" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# # Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinter"
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# # Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

visual_studio_code:
  settings_path: ~/workspace/dotfiles/vscode-settings.json
  extensions:
    - 4ops.terraform
    - github.copilot
    - github.copilot-chat
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - paulober.pico-w-go
    - redhat.ansible
    - redhat.vscode-yaml
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode

git_repos:
  - git@github.com:andrewcfitz/connect.git
  - git@github.com:fitz-biz/1password-connect.git
  - git@github.com:fitz-biz/Fitz.OnePassword.Connect.git
  - git@github.com:fitz-biz/Fitz.Peplink.Api.Client.git
  - git@github.com:fitz-biz/k3s-cluster1.git
  - git@github.com:fitz-biz/getalong.git
  - git@github.com:fitz-biz/shared-cluster.git
  - git@github.com:fitz-biz/ha-tools.git
  - git@github.com:fitz-biz/HAGpsSync.git
  - git@github.com:fitz-biz/louie-camp.git
  - git@github.com:fitz-biz/management.git
  - git@github.com:fitz-biz/monitor.git
  - git@github.com:fitz-biz/apps.git
  - git@github.com:fitz-biz/proget-k3s.git
  - git@github.com:fitz-biz/proxmox.git
  - git@github.com:fitz-biz/rvchecklist.git
  - git@github.com:fitz-biz/smtp-bridge.git

git_repos_to_switch_to_ssh:
  - name: dotfiles
    ssh_url: git@github.com:andrewcfitz/dotfiles.git
  - name: mac-dev-playbook
    ssh_url: git@github.com:andrewcfitz/mac-dev-playbook.git
