---
configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_oh_my_zsh: true
configure_xcode: true
configure_vscode_extensions: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - News
  - 'App Store'
  - Podcasts
  - 'System Settings'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/andrewcfitz/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/workspace/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc
  - .p10k.zsh

xcode_xip_filename: "Xcode-16.1.0.xip"
xcode_major_version: 16

homebrew_installed_packages:
  - artginzburg/tap/sudo-touchid  # Installing this early to avoid password prompts.
  - actionlint
  # - ansible # Installed via Pip.
  - ansible-lint
  - aria2
  - aws-nuke
  - awscli
  - bash
  - cabextract
  - cdrtools
  - chruby
  - cloudflare-wrangler2
  - coreutils
  - crane
  - exiftool
  - ffmpeg
  - figlet
  - fontconfig
  - gh
  - git
  - git-lfs
  - gnu-sed
  - helm
  - icu4c@76
  - iperf3
  - jq
  - k3sup
  - kompose
  - pulumi/tap/kube2pulumi
  - kubecm
  - kubernetes-cli
  - libusb
  - lsusb
  - sandreas/tap/m4b-tool
  - mas
  - ncdu
  - nmap
  - node
  - openapi-generator
  - postgresql
  - powerlevel10k
  - pulumi
  - rclone
  - ruby-install
  - s3cmd
  - sl
  - speedtest-cli
  - stow
  # - swiftlint
  - tcptraceroute
  - tfenv
  - util-linux
  - vim
  - watch
  - wget
  - wimlib
  - xcodes

homebrew_taps:
  - homebrew/bundle
  - isen-ng/dotnet-sdk-versions
  - sidneys/homebrew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - android-studio
  - audacity
  - balenaetcher
  - bartender
  - bluetility
  - charles
  - chatgpt
  - cinebench
  - cyberduck
  - dbeaver-community
  - discord
  - docker
  - dotnet-sdk7
  - dotnet-sdk8
  - dotnet-sdk9
  - element
  - firefox
  - font-hack-nerd-font
  - fork
  - github
  - google-chrome
  - iterm2
  - itermai
  - jetbrains-toolbox
  - kubecontext
  - microsoft-remote-desktop
  - mqtt-explorer
  - mysqlworkbench
  - ngrok
  - notion
  - obsidian
  - openinterminal
  - peripheryapp/periphery/periphery
  - postman
  - proton-mail
  - qflipper
  - rectangle
  - sf-symbols
  - stats
  - steam
  - tailscale
  - the-unarchiver
  - thonny
  - utm
  - vagrant
  - visual-studio-code
  - vlc
  - wireshark

# # See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_installed_app_ids: []
# mas_email: ""
# mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# # Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinter"
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# # Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

visual_studio_code_extensions:
  - 4ops.terraform
  - github.copilot
  - github.copilot-chat
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - paulober.pico-w-go
  - redhat.ansible
  - redhat.vscode-yaml
  - visualstudioexptteam.intellicode-api-usage-examples
  - visualstudioexptteam.vscodeintellicode
