---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/osx-command-line-tools.yml

    - import_tasks: tasks/oh-my-zsh.yml
      when: configure_oh_my_zsh
      tags: ['oh-my-zsh']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/homebrew.yml
      tags: ['homebrew']

    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/mas.yml
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - import_tasks: tasks/dock.yml
      when: configure_dotfiles
      tags: ['dock']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/xcode.yml
      when: configure_xcode
      tags: ['xcode']

    - import_tasks: tasks/nuget.yml
      when: configure_nuget
      tags: ['nuget']

    - import_tasks: tasks/vscode-extensions.yml
      when: configure_vscode_extensions
      tags: ['vscode-extensions']

    - import_tasks: tasks/git-repos.yml
      when: git_repos
      tags: ['git-repos']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
