---
- name: Install Visual Studio Code extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ lookup('env', 'USER') }}"
        visual_studio_code_extensions:
          - "{{ item.name | default(item) }}"
  loop: "{{ visual_studio_code.extensions }}"
  when: visual_studio_code.extensions is defined

- name: Create a symbolic link for vscode settings
  ansible.builtin.file:
    src: "{{ visual_studio_code.settings_path }}"
    dest: "~/Library/Application Support/Code/User/settings.json"
    owner: andrew
    group: staff
    state: link
    force: true
  when: visual_studio_code.settings_path is defined
