---
- name: Download Xcode
  ansible.builtin.get_url:
    url: http://mirror.fitz.biz/Xcode-16-latest.xip
    dest: /tmp/Xcode-16-latest.xip
    mode: '0660'

- name: Install Xcode
  include_role:
    name: macstadium.xcode
  vars:
    xcode_xip_location: '/tmp/Xcode-16-latest.xip'
    xcode_major_version: 16
