---
- name: Download Xcode
  ansible.builtin.get_url:
    url: "http://mirror.fitz.biz/{{ xcode_xip_filename }}"
    dest: "/tmp/{{ xcode_xip_filename }}"
    mode: "0660"

- name: Install Xcode
  include_role:
    name: tedgonzalez.xcodeinstall
  vars:
    xcode_xip_name: "{{ xcode_xip_filename }}"
    xcode_xip_path: "/tmp/{{ xcode_xip_filename }}"
    xcode_app_output_path: "/Applications/Xcode.app"
