---
- include_vars: ../secrets/apple.yml

- name: Install latest Xcode.
  command: xcodes install --latest
  changed_when: false
  failed_when: false
  check_mode: false
  environment:
    XCODES_USERNAME: '{{ appleid }}'
    XCODES_PASSWORD: '{{ appleid_password }}'
